Repository kodemia/website.kodemia.mx, pull requests merged in 2022-03, with the labels that each got.

#138 Refactor inputs
  components/Inputs/Input.tsx
  components/Inputs/PhoneInput.tsx
  components/Inputs/Select.tsx
  components/Inputs/TextArea.tsx
  package-lock.json
  styles/components/index.scss
  styles/components/inputs/index.scss
  styles/components/inputs/phone-input.scss
  styles/components/inputs/select.scss
  styles/utilities.scss
  tailwind.config.js
Labels: tailwind

#141 Refactor login
  components/Navbar.tsx
  components/Pages/Home/KodemiaFinancing.tsx
  components/Pages/Login/LoginForm.tsx
  pages/login.tsx
  styles/pages/index.scss
  styles/pages/login/form-login.scss
  styles/pages/login/index.scss
  styles/pages/login/login.scss
Labels: tailwind

#136 ♻️ Cards refactor
  components/BootcampCard.tsx
  components/Card.tsx
  components/EventCard.tsx
  components/H1.tsx
  components/H6.tsx
  components/HeroCard.tsx
  components/InfoBullet.tsx
  components/InfoCard.tsx
  components/LanguageCard.tsx
  components/LanguageInfo.tsx
  components/PageSection.tsx
  components/Pages/Bootcamps/CareerCoach.tsx
  components/Pages/Bootcamps/Goals.tsx
  components/Pages/Bootcamps/Support.tsx
  components/Pages/Companies/ChooseAKoder.tsx
  components/Pages/Companies/FindIdealKoder.tsx
  components/Pages/Companies/HelpFindTalent.tsx
  components/Pages/Companies/TalentDevelopment.tsx
  components/Pages/Home/KodemiaFinancing.tsx
  components/Pages/Home/OurBootcamps.tsx
  components/Pages/Home/OurMethod.tsx
  components/Pages/Home/Testimonials.tsx
  components/Pages/Home/WhyKodemia.tsx
  components/Text.tsx
  config/bootcamps/career-data.json
  package-lock.json
  pages/eventos.tsx
  stories/InfoContainer.stories.tsx
  styles/components/bootcamp-card.scss
  styles/components/bootcamps/goals.scss
  styles/components/bootcamps/index.scss
  styles/components/hero-card.scss
  styles/components/index.scss
  styles/components/info-card.scss
  styles/components/language-card.scss
  styles/pages/companies/find-ideal-koder.scss
  styles/pages/companies/help-find-talent.scss
  styles/pages/companies/index.scss
  styles/pages/companies/talent-development.scss
  styles/pages/home/index.scss
  styles/pages/home/our-bootcamps.scss
  styles/pages/home/our-method.scss
  styles/pages/home/why-kodemia.scss
  styles/utilities.scss
  tailwind.config.js
Labels: tailwind

#140 ♻️ Metrics refactor
  components/PageSection.tsx
  components/Pages/Bootcamps/MetricCard.tsx
  components/Pages/Bootcamps/Metrics.tsx
  components/Pages/Bootcamps/Scholarship.tsx
  components/Pages/Companies/CollaborateWithKodemia.tsx
  components/Pages/Companies/NextDeveloper.tsx
  components/Pages/Home/TransformYourLife.tsx
  pages/eventos.tsx
  styles/components/bootcamps/index.scss
  styles/components/bootcamps/metric-card.scss
  styles/components/bootcamps/metrics.scss
  styles/components/bootcamps/scholarship.scss
  styles/pages/companies/collaborate-with-kodemia.scss
  styles/pages/companies/index.scss
  styles/pages/companies/next-developer.scss
  tailwind.config.js
Labels: tailwind

#147 Refactor forms
  components/ApplyForm.tsx
  components/Forms/ApplyLandingForm.tsx
  components/Forms/MobileForm.tsx
  components/Inputs/Input.tsx
  components/Inputs/PhoneInput.tsx
  components/Inputs/Select.tsx
  components/Pages/Companies/RegisterForm.tsx
  pages/aplicar/index.tsx
  pages/empresas/registro/index.tsx
  styles/pages/companies/index.scss
  styles/pages/companies/register/index.scss
Labels: tailwind

#148 📝 Add pull request template
  .github/pull_request_template.md
Labels: enhancement

#151 ♻️ Hero Javascript refactor
  components/Pages/Bootcamps/Hero.tsx
  components/Pages/Bootcamps/HeroCard.tsx
  components/Pages/Bootcamps/HeroJsInfo.tsx
  components/Pages/Home/Hero.tsx
  components/Pages/Home/KodemiaFinancing.tsx
  pages/index.tsx
  pages/javascript-live.tsx
  styles/components/bootcamps/hero-card.scss
  styles/components/bootcamps/hero.scss
  styles/components/bootcamps/index.scss
Labels: tailwind

#149 Refactor/alliances kodemia
  components/CarrouselAlliances.tsx
  components/Pages/Home/AlliancesKodemia.tsx
  styles/components/carrousel-alliances.scss
  styles/components/index.scss
  styles/pages/home/alliances-kodemia.scss
  styles/pages/home/index.scss
Labels: tailwind

#153 🐛 Fix mentors query
  pages/mentores.tsx
Labels: bug

#154 :recycle: Hero Companies refactor
  components/Pages/Companies/Hero.tsx
  styles/pages/companies/hero.scss
  styles/pages/companies/index.scss
Labels: tailwind

#157 :recycle: Investment section refactor
  components/Pages/Bootcamps/Investment.tsx
  components/Pages/Bootcamps/Scholarship.tsx
  styles/components/bootcamps/index.scss
  styles/components/bootcamps/investment.scss
  tailwind.config.js
Labels: tailwind

#152 thank you page
  components/BigMessagePage.tsx
  components/Navbar.tsx
  config/navbar-items.json
  pages/404.tsx
  pages/aplicar/backbase/gracias.tsx
  pages/aplicar/gracias/[bootcamp].tsx
  pages/empresas/registro/gracias.tsx
  pages/login.tsx
  styles/pages/404.scss
  styles/pages/apply/index.scss
  styles/pages/apply/thanks.scss
  styles/pages/companies/register/thanks.scss
  styles/pages/index.scss
Labels: tailwind

#156 Clases page tailwind migration
  .github/pull_request_template.md
  components/Footer.tsx
  components/PageHero.tsx
  components/Pages/Classes/ClassCard.tsx
  pages/clases.tsx
  pages/eventos.tsx
  pages/mentores.tsx
  styles/pages/classes/class-card.scss
  styles/pages/classes/classes.scss
  styles/pages/classes/index.scss
  tailwind.config.js
Labels: tailwind
